### ISSUE TITLE
[Bug]: On spawn of a ship/plane, buttons can display the wrong value

### ISSUE THREAD

**Issue by checkraisefold** [Naval-Warfare-Remastered/Bug-Reports#14] opened 2022-02-13 02:29 UTC
### Describe the bug

For example, throttle and steer lock are on by default, but the buttons will display "OFF"

### Frequency

Every time I use a ship or plane

### Contact

checkraisefold#0001

### Where did this occur?

Development Server

**Comment by plainenglishh** [comment] 2022-02-13 02:34
duplicate of https://github.com/Naval-Warfare-Remastered/Bug-Reports/issues/10

**Closed as completed by plainenglishh** 2022-02-13 02:34 UTC
Labels: Bug, Duplicate
