### ISSUE TITLE
[Bug]: Plane spawns too close to each other on islands

### ISSUE THREAD

**Issue by Mustang2049** [Naval-Warfare-Remastered/Bug-Reports#20] opened 2022-02-13 02:40 UTC
### Describe the bug

When spawning a plane on an island, another player can despawn it by spawning another plane at the other spawn.

Steps to reproduce:
1. Spawn a plane at an island plane spawn.
2. Have someone spawn a plane at the other spawn directly after, before the cooldown is over.

Expected result: The first plane is unaffected.
Actual result: The first plane despawns.

https://user-images.githubusercontent.com/38600514/153735933-9c5d6583-19d4-4221-8a9d-7c23623c0ab8.mp4

### Frequency

Every time above steps are reproduced

### Contact

mustang#3083

### Where did this occur?

Development Server

**Comment by checkraisefold** [comment] 2022-02-13 02:41
Duplicate of #11

**Closed as completed** 2022-02-13 02:43 UTC
Labels: Bug, Duplicate
