### ISSUE TITLE
[Bug]: Aim Fail

### ISSUE THREAD

**Issue by O513** [Naval-Warfare-Remastered/Bug-Reports#29] opened 2022-02-13 02:57 UTC
### Describe the bug

Bug Description:** When aiming at any objects the area thats meant to shoot at doesnt hit, not due to skill  but the gun itseld. Its like theres some invisible block in an area im trying to shoot and its will shoot either above or below that invisible block but not at it. This probably has something to due with that + around the aiming reticle circle.
Reproducible:** Yes
Steps to Reproduce:** Shoot multiple times and see
Expected Result:** Hit/ hit but unintended/ hit but unintended
Actual Result:** Variable
Platform:** PC
Version:** 0.2.5
Attachments:** None

### Frequency

Its variable.

### Contact

O5-13 Pepsilon#4192

### Where did this occur?

Development Server

**Comment by checkraisefold** [comment] 2022-02-13 02:58
Duplicate of #15

**Comment by plainenglishh** [comment] 2022-02-13 02:59
^^^

**Closed as completed by plainenglishh** 2022-02-13 02:59 UTC
Labels: Bug, Duplicate
